name: Change Log
on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@main
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          head-ref: 'v0.0.2'
          base-ref: 'v0.0.1'
      - name: Get the changelog
        run: echo "${{ steps.changelog.outputs.changelog }}"
      - name: Generate changelog from release
        id: release
        uses: metcalfc/changelog-generator@main
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the changelog
        run: echo "${{ steps.release.outputs.changelog }}"