name: Deploy and Secure Static Website

on:
  pull_request:
    branches: [ main ]

jobs: 
  job_1: 
    name: Check the current status of the cloud formation stack
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Import environment variables from .env
      shell: bash
      run: |
        cd authenticated-cloud-docs
        pwd && ls -a
        input=".env"
        SUB='AUTHENTICATED_CLOUD_DOCS__HOSTED_ZONE_SUBDOMAIN'
        while read -r line
        do
          if [[ "$line" == *"$SUB"* ]]; then
            echo "$line" >> $GITHUB_ENV
          fi
        done < "$input"
    
    - name: Check the CF statck status
      env:
        ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        cd ./authenticated-cloud-docs/deployment/cfStatus 
        touch .env
        echo "ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
        echo "SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}" >> .env
        echo "AWS_REGION=us-east-1" >> .env
        echo "CF_STACK_NAME=${{ env.AUTHENTICATED_CLOUD_DOCS__HOSTED_ZONE_SUBDOMAIN }}-dev"
        npm install
        npm start >> output.txt
        cat output.txt